version: '3.2'

services: 
    python:
        image: python_env_test_21/python:1.0
        build: ./python
        container_name: 'env_test_21_python'
        stdin_open: true
        tty: true
        working_dir: '/tmp/work'
        volumes: 
            - ../python:/tmp/work